errors:
    response:
        DB: 
            CONNECTIVITY: "Connection to the Database has failed"
            QUERY_EXECUTION: "An issue has occurred with the query call to the database"
            RETRY_EXHAUSTED: "The number of retries has been exhausted"
            BAD_SQL_SYNTAX: "The SQL Syntax used in the call to the database is incorrect"
            DEFAULT: "An Error has occurred with the database call."
        BUSINESS: 
            DEFAULT: "A business use case error has occurred."
        DEFAULT: 
            DEFAULT: "An error has occurred with the integration."
        SFTP: 
            RETRY_EXHAUSTED: "The amount of retries for SFTP processing have been exceeded."
            ILLEGAL_PATH: "The SFTP path specified is illegal."
            FILE_ALREADY_EXISTS: "The file already exists within the defined directory."
            CONNECTIVITY: "The SFTP is having connectivity issues."
            ACCESS_DENIED: "The defined user does not have access to this location."
            FILE_LOCK: "This file is currently being modified by another user"
            ILLEGAL_CONTENT: "The content provided is not able to be processed by the SFTP server."
            DEFAULT: "An error has occurred during SFTP processing."
        SALESFORCE: 
            LIMIT_EXCEEDED: "The amount of requests to Salesforce has exceeded the api limit."
            CONNECTIVITY: "There are issues connecting to Salesforce with the provided authentication."
            INVALID_RESPONSE: "An invalid resposne was received from Salesforce."
            RETRY_EXHAUSTED: "The amount of retries have been exhausted."
            TIMEOUT: "The Salesforce connection has timed out."
            MUTUAL_AUTHENTICATION_FAILED: "The session could not be authenticated for use with the Salesforce REST API."
            NOT_FOUND: "The Salesforce instance was not found."
            INVALID_INPUT: "The request data sent to Salesforce was invalid."
        HTTP:
            BAD_GATEWAY : "Bad HTTP gateway"
            BAD_REQUEST : "Bad request" 
            CLIENT_SECURITY: "Client ID/Secret is incorrect"
            CONNECTIVITY: "Connectivity Issue"
            FORBIDDEN: "Forbidden Path" 
            INTERNAL_SERVER_ERROR: "Internal Server Error"
            METHOD_NOT_ALLOWED: "The method used is not allowed"
            NOT_ACCEPTABLE: "The request to the HTTP is not acceptable"
            NOT_FOUND: "The HTTP url was not found"
            PARSING: "A parsing error has occurred" 
            RETRY_EXHAUSTED: "The amount of retries has been exceeded" 
            SECURITY: "A security error has occurred" 
            SERVICE_UNAVAILABLE: "The service is currently unavailable" 
            TIMEOUT: "The http endpoint has timed out"
            TOO_MANY_REQUESTS: "There have been too many requests to the server" 
            UNAUTHORIZED: "The authentication given is not authorized for this endpoint"
            UNSUPPORTED_MEDIA_TYPE: "The defined media type is incorrect" 
            DEFAULT: "An unidentified HTTP error has occurred."
        APIKIT:
            BAD_REQUEST: "HTTP Code: 400.  Bad Request" 
            NOT_FOUND: "HTTP Code: 404. Resource Not Found"
            METHOD_NOT_ALLOWED: "HTTP Code: 405. Method not allowed"
            NOT_ACCEPTABLE: "HTTP Code: 406. Not acceptable"
            UNSUPPORTED_MEDIA_TYPE: "HTTP code: 415. Unsupported media type"
            DEFAULT: "HTTP code: 500. An undefined server error has occurred."
email:
  host: "smtp.gmail.com"
  port: "587"
  username: "madelyn.odell@mtxb2b.com"
  password: "necszymdelwextxh"